name: mediconnect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  flutter:
    sdk: flutter
  http: ^1.2.2
  cached_network_image: ^3.2.3
  intl: ^0.17.0 
  charts_flutter_new: ^0.12.0
  flutter_rating_bar: ^4.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true